# Sibilla Config Template

# Config Version
version = 1

[dev]
# fatal, error, warning, info, debug, trace
log_level = "info"

[Sibilla]

[Adapter]
[Adapter.OneBotCfg]
connect_type = "wsr"
ws_url = "ws://example.com"
access_token = "1234"

[ChatBot]
[ChatBot.Liz]
adpater = "OneBotAdapter"
adpaterCfg = "OneBotCfg"
bot_id = "123456789"
admin_id = "987654321"
